### ISSUE TITLE
bug: opening already-open app with Finder does not bring app to focus using some browser engines

### ISSUE THREAD

**Issue by gldnspud** [webcatalog/chromeless#44]
# Bug Report
**Specifications:**
- App Version: chromeless v1.6.1
- OS (macOS, Windows, Linux): macOS 11.4

**Description:**

If a chromeless-built browser app is already open, when you double-click on the app's icon in Finder, or use some other way of opening it (such as via Alfred, the `open` command in terminal, etc.), it should bring the app into focus.

Currently, when you do this, nothing happens. The only way to switch to the app is to use Cmd+Tab or to click on it in the dock.

**Steps to Reproduce:**

Create a chromeless app using one of the engines that has the issue: Vivaldi tabbed, Brave tabbed, Edge tabbed.

Go to the `~/Applications/Chromeless Apps` folder.

Open the app.

Switch back to Finder.

Open the app again. This is where expected behavior deviates from actual behavior for certain engines.

**Additional Context**

These were successful:

- WebKit standard.

These were partially successful:

- Firefox tabbed: app comes into focus, but new tab is created. (expected behavior is no new tab created)

If I install more browsers and try out more engines I'll update this issue.

**Comment by jeffpoulton** [comment]
I have a similar issue that may or may not be related. On macOS I use an application called Choosy to pick which browser should open a URL. If I pick a Chromeless browser to open a URL and the browser is not running, the browser opens to the desired URL. However, if the Chromeless browser is already open, nothing happens. I do not have this problem with any other non-Chromeless browser.

**Comment by quanglam2807** [comment]
This is pretty much a limitation of Chromeless :( For now, if you need to use Choosy, please use WebCatalog (https://webcatalog.app) instead. Btw, you can also try out Switchbar: it's similar to Choosy but has WebCatalog integration support: https://switchbar.app

**Comment by ldub** [comment]
Hey @quanglam2807 can you provide any more detail on why this is a limitation of chromeless? This is pretty essential functionality and I'd love to understand if this can be fixed eventually and if I could help somehow.

**Comment by quanglam2807** [comment]
@ldub Thanks for asking.

Chromeless works by using bash script. The bash script launches the Chromium/Firefox engine with a list of parameters (e.g. `.../Chromium --url="https://google.com"`).  So in many cases, macOS either points to the bash script or the browser binary for running - both causing problems (#20, #44, #59, #64). 

For example, if after launching the app for the first time, what lives on the Dock is the browser binary, not the bash script. So if you pin the icon on Dock, quit the app and click on that icon, macOS will load the browser binary without parameters instead of the bash script.

**Comment by ldub** [comment]
I see, thanks for the explanation. I can see that others have already pointed you at epichrome, which functioned similarly and was able to get past this problem. Chromeless is the only FOSS alternative to epichrome as far as I can tell, and epichrome has announced an EOL so a lot of users will probably migrate to chromeless. 

I wonder if you could reach out to @dmarmor directly and ask how this issue was fixed in Epichrome?

Lastly, I appreciate your work and would be more than happy to sponsor you via GitHub or Patreon, if you have something like that set up.

**Comment by quanglam2807** [comment]
Thank you, @ldub. I tried Epichrome and it also had some similar issues I mentioned above. But I'll look deeper into how Epichrome works when I have time. 

To be honest, because of Chromeless's limitations, we mostly focus on WebCatalog's development these days: https://webcatalog.io/webcatalog/. I think the only major difference between Chromeless and WebCatalog is extension support. 

> Lastly, I appreciate your work and would be more than happy to sponsor you via GitHub or Patreon, if you have something like that set up.
Thank you! Chromeless is currently funded by other income sources of WebCatalog Ltd: https://webcatalog.io/ so if you'd like to support us, feel free to other products from us.

**Comment by ldub** [comment]
Yeah, I tried out webcatalog, which looks great but it doesn't fit my use case because the apps can't have browser tabs. I read through the [skywhale issue](https://github.com/webcatalog/webcatalog-app/issues/1517) and that looks similar to my use case. I rely on chrome extensions for a lot of things and would need those to be stable as well, looks like they are possible to use with webcatalog now but I haven't tested my workflow extensively.

Epichrome did sometimes have issues with docking the apps or opening w/ `open -a` (or choosy or whatnot) but it usually works fine. 

Anyway thanks for the prompt replies, I'll be patiently waiting to try skywhale and may end up a webcatalog customer anyway for some apps I use that don't need tabs.
