### ISSUE TITLE
bug: Chromeless Helper extension prevents 'New Window' for browser

### ISSUE THREAD

**Issue by gregschroeder** [webcatalog/chromeless#88]
# Bug Report
**Specifications:**
- App Version: Version v4.2.1
- OS (macOS, Windows, Linux): macOS 12.1

**Description:**
Chromeless Helper extension, if enabled, prevents opening a new window (File->New Window) in a Chromeless browser app.

**Steps to Reproduce:**
1. Create new browser in Chromeless (eg, TestMe, using Chrome)
2. Open TestMe
3. Attempt to create new window (cmd-N, or File->New Window)
4. New window flashes and immediately closes
5. Disable Chromeless Helper
6. Create new window works fine
7. Enable Chromeless Helper
8. goto 3

**Comment by twooster** [comment]
I also had this issue. The fix is fairy simple if you're a technical user:

* Chrome Preferences
* Extensions
* Chromeless Browser -> Details
* Source -> Loaded from: -> click the url, opens a finder window
* Find `background.js` and open it in a text editor
* Comment out the `if` block starting with: `  if (!lastWindowSessionID) {`
* Save, close, and restart the browser (or reload the extension)

This was evidently added to fix some other bug that I've never experienced (https://github.com/webcatalog/chromeless/issues/59) but it ruins usability if you're using Chromeless to split out complete browser sessions instead of an app container.
